### ISSUE TITLE
Remove log4j.xml from jar file

### ISSUE THREAD

**Issue by murillo128** [AuthorizeNet/sdk-java#109]
It has broken all the loggin of my jboss application and got me crazy until I found this. Not sure if it is a way to everride it, but it should not re-define the root logger

**Comment by gnongsie** [comment]
Hi, I'm sorry but I cannot find this xml file in the Authorize.Net Java SDK v1.9.2 jar file. Can you provide more information regarding the version of the jar you are using and the issue you faced?

**Comment by murillo128** [comment]
Sorry, my bad, dislexia.. :)

I meant the log4j.properties on the resource folder that is copied into the jar file:

**Comment by rahulrnitc** [comment]
Hi @murillo128, 
 If you are still facing the issue you can try the solution suggested here: https://github.com/AuthorizeNet/sdk-java/pull/101

**Comment by gnongsie** [comment]
Thank you for raising this issue. We have had some releases since the issue was raised, and we hope that these updates have resolved your asks. We hope the suggested fix has also provided some help. We are therefore closing this issue. Please raise a new issue, if you’re still facing problems, and we’ll look into it quickly.
