### ISSUE TITLE
XmlTreeUtil needs to escape attribute values & text nodes

### ISSUE THREAD

**Issue by james-jory** [AuthorizeNet/sdk-java#43]
XmlTreeUtil._printTree currently does not escape attribute values or text nodes. This causes parsing errors when incorrectly formatted XML is submitted.

**Comment by kikmak42** [comment]
Hi James,
I observed the SDK already escapes for `&`, `>` and `<`, but `"` and `'` are ignored.
Also the Authorize.Net API accepts all data in XML element instead of attributes, as a result I see no need to escape the remaining characters.

Could you please provide the code which produced the error, along with the transaction data you were sending in the request.

Regards
Kaushik

**Comment by brianmc** [comment]
Closing this one, thanks for the PR James.

**Comment by james-jory** [comment]
@kikmak42, I'm just now getting back to syncing our patched build of the AuthNet library with the latest changes I noticed your comment.

As you see in my pull request, there is no escaping taking place for attributes and text values and there is a unit test that proves that the SDK is not escaping. The current code just blindly writes to the OutputStream. Just run the unit test provided in the PR against the current version of the SDK and you will see that it fails on a parsing error.

It would be helpful if you could point where you're seeing the SDK doing the escaping. Without the fixes in the PR provided, we get API failures when text values contain unescaped characters.

Thanks,
James

**Comment by james-jory** [comment]
@kikmak42 I'm retesting with the latest version of SDK now and see that the escaping is working properly. Will continue to test and dig back into our original issue to track down why I thought escaping change was needed.

-James
