### ISSUE TITLE
No connection time out and read time out for http calls.

### ISSUE THREAD

**Issue by sureshkarthi** [AuthorizeNet/sdk-java#62]
No connection time out and read time out for http calls.

**Comment by Nvn1912** [comment]
Any updates?

**Comment by brianmc** [comment]
Definitely something we've considered adding into our configuration.  Interested if you are having problems with specific APIs timing out too soon or too late?

**Comment by mattdrees** [comment]
@brianmc I'd be interested in these.

We've had issues with connection timeouts, most recently https://status.authorize.net/incidents/flfhlffmbdbg and https://status.authorize.net/incidents/flphcdpjjgfh.

Our code is currently using as much of the SDK code as we can but is maintaining its own `HttpClient` for the api calls so that we can set up timeouts. I'd be nice to not have to do this.

**Comment by mattdrees** [comment]
In fact I'll make a PR if you tell me roughly what you're looking for, API-wise.

**Comment by brianmc** [comment]
Hi @mattdrees thanks for this.   We were thinking we'd support this in the same way we'd support HTTP proxy settings, so a new constant in https://github.com/AuthorizeNet/sdk-java/blob/79709280c668156e9becc9b5f62450b755cae7e0/src/main/java/net/authorize/util/Constants.java and then passing that to httpclient in https://github.com/AuthorizeNet/sdk-java/blob/485aa5be982b1bb56c3358d7891eb91677607efa/src/main/java/net/authorize/util/HttpClient.java 

If you can make the PR into our future branch that would be great, thanks again.

Brian

**Comment by brianmc** [comment]
Added in latest release 1.8.7. Thanks again for the suggestion.

**Comment by mattdrees** [comment]
Thanks @brianmc . Sorry I didn't get around to a PR myself; maybe next time.
